### ISSUE TITLE
installation error on ubuntu 22.04 and python 3.10

### ISSUE THREAD

**Issue by schristley** [tapis-project/tapipy#62]
I'm getting an install error but not sure what is the cause. Building a simple docker image with ubuntu 22.04 and the stock python 3.10

```
root@eec3385f8f4f:/# pip3 install tapipy
Collecting tapipy
  Downloading tapipy-1.6.3-py3-none-any.whl (276 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 276.5/276.5 KB 4.1 MB/s eta 0:00:00
Collecting atomicwrites<2.0.0,>=1.4.0
  Downloading atomicwrites-1.4.1.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Collecting pyyaml>=5.4
  Downloading PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.5/705.5 KB 15.2 MB/s eta 0:00:00
Requirement already satisfied: six<2.0,>=1.10 in /usr/lib/python3/dist-packages (from tapipy) (1.16.0)
Requirement already satisfied: setuptools>=21.0.0 in /usr/lib/python3/dist-packages (from tapipy) (59.6.0)
Collecting cloudpickle>=1.6.0
  Downloading cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting jsonschema>=3.2.0
  Downloading jsonschema-4.22.0-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 KB 24.3 MB/s eta 0:00:00
Collecting certifi>=2020.11.8
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 KB 31.8 MB/s eta 0:00:00
Collecting openapi_spec_validator<0.6.0,>=0.5.0
  Downloading openapi_spec_validator-0.5.7-py3-none-any.whl (32 kB)
Collecting PyJWT>=1.7.1
  Downloading PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting openapi_core==0.16.0
  Downloading openapi_core-0.16.0-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 KB 18.7 MB/s eta 0:00:00
Collecting python_dateutil<3.0.0,>=2.5.3
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 55.6 MB/s eta 0:00:00
Requirement already satisfied: urllib3<2.0.0,>=1.26.5 in /usr/lib/python3/dist-packages (from tapipy) (1.26.5)
Collecting cryptography>=3.3.2
  Downloading cryptography-42.0.7-cp39-abi3-manylinux_2_28_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 40.1 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/lib/python3/dist-packages (from tapipy) (2.25.1)
Collecting typing-extensions<5.0.0,>=4.3.0
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting openapi-schema-validator<0.4.0,>=0.3.0
  Downloading openapi_schema_validator-0.3.4-py3-none-any.whl (9.8 kB)
Collecting more-itertools
  Downloading more_itertools-10.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 KB 15.4 MB/s eta 0:00:00
Collecting jsonschema-spec<0.2.0,>=0.1.1
  Downloading jsonschema_spec-0.1.6-py3-none-any.whl (12 kB)
Collecting pathable<0.5.0,>=0.4.0
  Downloading pathable-0.4.3-py3-none-any.whl (9.6 kB)
Collecting parse
  Downloading parse-1.20.1-py2.py3-none-any.whl (20 kB)
Collecting werkzeug
  Downloading werkzeug-3.0.3-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.3/227.3 KB 39.5 MB/s eta 0:00:00
Collecting isodate
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 7.3 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.9/443.9 KB 7.9 MB/s eta 0:00:00
Collecting attrs>=22.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 KB 14.0 MB/s eta 0:00:00
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 40.0 MB/s eta 0:00:00
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.35.1-py3-none-any.whl (26 kB)
Collecting jsonschema>=3.2.0
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 KB 16.4 MB/s eta 0:00:00
Collecting lazy-object-proxy<2.0.0,>=1.7.1
  Downloading lazy_object_proxy-1.10.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.3/68.3 KB 15.7 MB/s eta 0:00:00
Collecting openapi_spec_validator<0.6.0,>=0.5.0
  Downloading openapi_spec_validator-0.5.6-py3-none-any.whl (31 kB)
  Downloading openapi_spec_validator-0.5.5-py3-none-any.whl (32 kB)
  Downloading openapi_spec_validator-0.5.4-py3-none-any.whl (32 kB)
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 KB 31.4 MB/s eta 0:00:00
Collecting requests<3.0.0,>=2.20.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 18.9 MB/s eta 0:00:00
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.7/117.7 KB 36.3 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.20.0->tapipy) (3.3)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 KB 7.4 MB/s eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Building wheels for collected packages: atomicwrites
  Building wheel for atomicwrites (setup.py) ... done
  Created wheel for atomicwrites: filename=atomicwrites-1.4.1-py2.py3-none-any.whl size=6957 sha256=7667faa02a6ba4cb0b51bfddca9a9ed34028e4d99e352d2a21c3f54c5e827c0a
  Stored in directory: /root/.cache/pip/wheels/34/07/0b/33b15f68736109f72ea0bb2499521d87312b932620737447a2
Successfully built atomicwrites
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

**Comment by schristley** [comment]
Here's the Dockerfile

```
FROM ubuntu:22.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --fix-missing \
    git \
    python3 \
    python3-pip \
    python3-sphinx \
    python3-scipy \
    python3-venv \
    libyaml-dev \
    wget \
    curl \
    jq \
    bsdmainutils \
    nano \
    rsync

RUN pip3 install tapipy
```

**Comment by schristley** [comment]
seems to install ok with ubuntu 20.04 and python 3.8
